CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`content` text NOT NULL,
	`excerpt` text,
	`category` varchar(100),
	`tags` text,
	`status` enum('draft','review','published','scheduled') NOT NULL DEFAULT 'draft',
	`seoTitle` varchar(255),
	`seoDescription` text,
	`coverImageUrl` text,
	`publishedAt` timestamp,
	`scheduledFor` timestamp,
	`generatedByAI` boolean NOT NULL DEFAULT false,
	`aiPrompt` text,
	`wordpressPostId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
