CREATE TABLE `ad_creatives` (
  `id` int AUTO_INCREMENT NOT NULL,
  `userId` int NOT NULL,
  `briefTitle` varchar(200) NOT NULL,
  `briefDescription` text NOT NULL,
  `campaignType` varchar(100),
  `targetAudience` varchar(200),
  `product` varchar(200),
  `colorPalette` varchar(200),
  `textOverlay` varchar(300),
  `driveReferenceFolder` varchar(100),
  `driveReferenceFileId` varchar(100),
  `imageBase64` longtext,
  `imageUrl` text,
  `imageHash` varchar(100),
  `generatedHeadline` varchar(200),
  `generatedBody` text,
  `status` enum('pending_generation','generated','pending_approval','approved','rejected','uploading','executed','failed') NOT NULL DEFAULT 'pending_generation',
  `rejectionReason` text,
  `metaAdId` varchar(100),
  `campaignId` varchar(100),
  `adSetId` varchar(100),
  `errorMessage` varchar(500),
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `ad_creatives_id` PRIMARY KEY(`id`)
);
